### ISSUE TITLE
package.json中vue的版本配置是否有问题？

### ISSUE THREAD

**Issue by cookcoder** [luoyunchong/lin-cms-vvlog#25]
git clone后，执行yarn 和yarn upgrade element-ui，运行yarn serve的时候，一直提示This dependency was not found: * swiper/css/swiper.css。

如果不执行yarn upgrade element-ui，运行就会出现Cannot read property ‘parseComponent’ of undefined.

**Comment by luoyunchong** [comment]
试下最新的代码。

**Comment by cookcoder** [comment]
谢谢，可以了！
